name: Deployment
on:
  push:
    branches:
      - main
      - dev
      - try-docker
env:
  MONGODB_DB_NAME: company
jobs:
  test:
    environment: dev
    runs-on: ubuntu-latest
    container: node:20
    env:
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_CLUSTER_ADDRESS: cluster0.dqwwk5n.mongodb.net
      PORT: 7000
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "MONGODB USERNAME :${{ env.MONGODB_USERNAME}} "  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB db :${{ env.MONGODB_DB_NAME}} "  
